### ISSUE TITLE
Bug: `:color text-to-coloescheme` doesn't seem to apply the `hex_palettes.default_palette` I saved

### ISSUE THREAD

**Issue by nyngwang** [svermeulen/text-to-colorscheme#4]
As title.

**Comment by nyngwang** [comment]
Well, I found it :) The documentation is incorrect in that `default_palette` should be put under `setup.default_palette` instead of `setup.hex_palettes.default_palette`.

**Comment by svermeulen** [comment]
Oh oops, thanks for reporting this.  Fixed the docs now.
