### ISSUE TITLE
The same result when using different query sentences.

### ISSUE THREAD

**Issue by nyngwang** [svermeulen/text-to-colorscheme#8]
Sometimes different query sentences lead me to the same colorscheme result. It will be great to make sure that all the color-related(including metaphor) words will involve in the result colorscheme.

**Comment by svermeulen** [comment]
One thing that might help, if your goal is to get more different results, is to modify the value for "temperature".  I just committed a change that added this to the user settings, which by default was set to 0.  If you set that to something higher like 0.8 you should get more variation in the responses

**Comment by nyngwang** [comment]
Thanks for the update! Let me try it and see if it can close this issue.
